apiVersion: batch/v1
kind: Job
metadata:
  name: replace-demo
  namespace: wave-demo
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  template:
    spec:
      containers:
      - name: demo
        image: busybox
        command: ["echo", "Using Replace sync option"]
      restartPolicy: Never
